## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file dpg_lin_adv.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_65 = Integer(65); _sage_const_60 = Integer(60); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100); _sage_const_104 = Integer(104); _sage_const_78 = Integer(78); _sage_const_96 = Integer(96); _sage_const_0 = Integer(0)## This file (dpg_lin_adv.sagetex.sage) was *autogenerated* from dpg_lin_adv.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('dpg_lin_adv', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_60 
_st_.blockbegin()
try:
 var('a,b,c')
 var('h')
 var('i,j,k,l')
 assume(i,j,k,l,'integer')
except:
 _st_.goboom(_sage_const_65 )
_st_.blockend()
_st_.current_tex_line = _sage_const_78 
_st_.blockbegin()
try:
 assume(a>_sage_const_0 )
 #c = 0
 b = -c
 
 A = matrix(SR,_sage_const_4 ,_sage_const_4 )
 A[:,:] = matrix(_sage_const_4 ,_sage_const_4 ,[[a+_sage_const_2 *b+c,a-c,-b,b],
                      [a-c,_sage_const_4 /h+a+_sage_const_2 *b+c,-b,b],
                      [-b,-b,a+_sage_const_2 *b+c,a-c],
                      [b,b,a-c,_sage_const_4 /h+a+_sage_const_2 *b+c]
                     ])
 b = matrix(SR,_sage_const_4 ,_sage_const_1 ,[_sage_const_1 ,_sage_const_1 ,-_sage_const_1 ,_sage_const_1 ])
 coef = A * BackslashOperator() * b
 
 for i in range(_sage_const_0 ,_sage_const_4 ):
     coef[i] = (coef[i]).apply_map(lambda x: x.rational_simplify().expand().full_simplify())
 
 
except:
 _st_.goboom(_sage_const_96 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_100 
 _st_.inline(_sage_const_0 , latex(A))
except:
 _st_.goboom(_sage_const_100 )
try:
 _st_.current_tex_line = _sage_const_104 
 _st_.inline(_sage_const_1 , latex(coef))
except:
 _st_.goboom(_sage_const_104 )
_st_.endofdoc()

